core/urls.py
from django.urls import path
from .views import (HomeView, 
                    ItemDetailView, 
                    CheckoutView,
                    PaymentView, 
                    add_to_cart, 
                    remove_from_cart, 
                    remove_single_item_from_cart, 
                    OrderSummaryView,
                    AddCouponView,
                    RequestRefundView)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='item-list_url'),
    path('checkout', CheckoutView.as_view(), name='checkout_url'),
    path('order-summary', OrderSummaryView.as_view(), name='order-summary_url'),
    path('product/<slug>', ItemDetailView.as_view(), name='product_url'),
    path('add-product/<slug>', add_to_cart, name='add-product_url'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon_url'),
    path('remove-product/<slug>', remove_from_cart, name='remove-product_url'),
    path('remove-single-product/<slug>', remove_single_item_from_cart, name='remove-single-product_url'),
    path('payment/<payment_option>',PaymentView.as_view(),name='payment_url'),
    path('request-refund',RequestRefundView.as_view(),name='request-refund_url')
]

templates/includes/footer.html
<!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
      
      <hr class="my-4" />

      <!-- Social icons -->
      <div class="pb-4">
        <a href="https://www.facebook.com/mdbootstrap" target="_blank">
          <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <a href="https://twitter.com/MDBootstrap" target="_blank">
          <i class="fab fa-twitter mr-3"></i>
        </a>

        <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
          <i class="fab fa-youtube mr-3"></i>
        </a>

        <a
          href="https://plus.google.com/u/0/b/107863090883699620484"
          target="_blank"
        >
          <i class="fab fa-google-plus-g mr-3"></i>
        </a>

        <a href="https://dribbble.com/mdbootstrap" target="_blank">
          <i class="fab fa-dribbble mr-3"></i>
        </a>

        <a href="https://pinterest.com/mdbootstrap" target="_blank">
          <i class="fab fa-pinterest mr-3"></i>
        </a>

        <a
          href="https://github.com/mdbootstrap/bootstrap-material-design"
          target="_blank"
        >
          <i class="fab fa-github mr-3"></i>
        </a>

        <a href="http://codepen.io/mdbootstrap/" target="_blank">
          <i class="fab fa-codepen mr-3"></i>
        </a>
      </div>
      <!-- Social icons -->

      <!--Copyright-->
      <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank">
          MDBootstrap.com
        </a>
      </div>
      <!--/.Copyright-->
    </footer>
    <!--/.Footer-->

templates/includes/navbar.html
{% load cart_template_tags %}
<!-- Navbar -->
  <nav
    class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar"
  >
    <div class="container">
      <!-- Brand -->
      <a
        class="navbar-brand waves-effect"
        href={% url 'core:item-list_url' %}
      >
        <strong class="blue-text">ECommerce</strong>
      </a>

      <!-- Collapse -->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item">
            <a class="nav-link waves-effect" href={% url 'core:item-list_url' %}>
            Home
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link waves-effect"
              href={% url 'core:checkout_url' %}
              >Checkout Page
              </a
            >
          </li> {% endcomment %}
          
        </ul> 

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href={% url 'core:order-summary_url' %} class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{request.user|cart_item_tag}} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a href={% url 'account_logout' %} class="nav-link waves-effect">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a href={% url 'account_login' %} class="nav-link waves-effect">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a href={% url 'account_signup' %} class="nav-link waves-effect">
              <span class="clearfix d-none d-sm-inline-block"> Sing up </span>
            </a>
          </li>
        {% endif %}
          <li class="nav-item">
            <a
              href="https://www.facebook.com/mdbootstrap"
              class="nav-link waves-effect"
              target="_blank"
            >
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="nav-item">
            <a
              href="https://twitter.com/MDBootstrap"
              class="nav-link waves-effect"
              target="_blank"
            >
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          <li class="nav-item">
            <a
              href="https://github.com/mdbootstrap/bootstrap-material-design"
              class="nav-link border border-light rounded waves-effect"
              target="_blank"
            >
              <i class="fab fa-github mr-2"></i>MDB GitHub
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar -->
  <div style='margin:80px 40px 0px 40px;'>
  {% if messages %}
  
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
  
  {% endif %}
  </div>
  

templates/includes/order_snippet.html
<div class="col-md-12 mb-4">
  <!-- Heading -->
  <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
  </h4>

  <!-- Cart -->
  <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">
          {{order_item.quantity}} x {{order_item.item.title}}
        </h6>
        <small class="text-muted">{{order_item.item.description}}</small>
      </div>
      <span class="text-muted">${{order_item.get_total_price}}</span>
    </li>
    {% endfor %}

    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
      <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{order.coupon.code}}</small>
      </div>
      <span class="text-success">-${{order.coupon.amount}}</span>
    </li>
    <li class="list-group-item d-flex justify-content-between">
      <span>Total (USD)</span>
      <strong>${{order.get_total}}</strong>
    </li>
    {% endif %}
  </ul>
  <!-- Cart -->

  {% if DISPLAY_COUPON_FORM %}
  <!-- Promo code -->
  <form class="card p-2" action={% url 'core:add-coupon_url' %} method='POST'>
    {% csrf_token %}
    <div class="input-group">
      {{couponForm.code}}
      <div class="input-group-append">
        <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">
          Redeem
        </button>
      </div>
    </div>
  </form>
  <!-- Promo code -->
  {% endif %}
</div>

templates/includes/scripts.html
 {% load static %}  
    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src={% static "js/jquery-3.4.1.min.js" %}></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src={% static "js/popper.min.js" %}></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src={% static "js/bootstrap.min.js" %}></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src={% static "js/mdb.min.js" %}></script>
    <!-- Initializations -->
    <script type="text/javascript">
      // Animations initialization
      new WOW().init();
    </script>