core/urls.py
from django.urls import path
from .views import (HomeView, 
                    ItemDetailView, 
                    CheckoutView,
                    PaymentView, 
                    add_to_cart, 
                    remove_from_cart, 
                    remove_single_item_from_cart, 
                    OrderSummaryView,
                    AddCouponView,
                    RequestRefundView)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='item-list_url'),
    path('checkout', CheckoutView.as_view(), name='checkout_url'),
    path('order-summary', OrderSummaryView.as_view(), name='order-summary_url'),
    path('product/<slug>', ItemDetailView.as_view(), name='product_url'),
    path('add-product/<slug>', add_to_cart, name='add-product_url'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon_url'),
    path('remove-product/<slug>', remove_from_cart, name='remove-product_url'),
    path('remove-single-product/<slug>', remove_single_item_from_cart, name='remove-single-product_url'),
    path('payment/<payment_option>',PaymentView.as_view(),name='payment_url'),
    path('request-refund',RequestRefundView.as_view(),name='request-refund_url')
]

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.db.models.signals import post_save

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50,blank=True,null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Item(models.Model):
    SHIRT = 'S'
    SPORT_WEAR = 'SW'
    OUTWEAR = 'OW'
    CATEGORY_CHOICES = [
        (SHIRT, 'Shirt'),
        (SPORT_WEAR, 'Sport Wear'),
        (OUTWEAR, 'Outwear'),
    ]

    PRIMARY = 'P'
    SECONDARY = 'S'
    DANGER = 'D'
    LABEL_CHOICES = [
        (PRIMARY, 'primary'),
        (SECONDARY, 'secondary'),
        (DANGER, 'danger'),
    ]
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product_url", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("core:add-product_url", kwargs={"slug": self.slug})
    
    def get_remove_from_cart_url(self):
        return reverse("core:remove-product_url", kwargs={"slug": self.slug})



class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'
    
    def get_total_price(self):
        if self.item.discount_price:
            return self.quantity * self.item.discount_price
        return self.quantity * self.item.price


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20,blank=True,null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address',related_name='billing_address',on_delete=models.SET_NULL,blank=True,null=True)
    shipping_address = models.ForeignKey('Address',related_name='shipping_address',on_delete=models.SET_NULL,blank=True,null=True)
    payment = models.ForeignKey('Payment',on_delete=models.SET_NULL,blank=True,null=True)
    coupon = models.ForeignKey('Coupon',on_delete=models.SET_NULL,blank=True,null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_price()
        if self.items.all() and self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    BILLING = 'B'
    SHIPPING = 'S'
    ADDRESS_CHOICES = [
        (BILLING, 'billing'),
        (SHIPPING, 'shipping')
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1,choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,blank=True,null=True)
    amount = models.FloatField()
    timestap = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

class Refund(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f'{self.pk}'

def userprofile_receiver(sender,instance,created,*args,**kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)

post_save.connect(userprofile_receiver,sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />

    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"
    />
    <!-- Bootstrap core CSS -->
    <link href={% static "css/bootstrap.min.css" %} rel="stylesheet" />
    <!-- Material Design Bootstrap -->
    <link href={% static "css/mdb.min.css" %} rel="stylesheet" />
    <!-- Your custom styles (optional) -->
    <link href={% static "css/style.css" %} rel="stylesheet" />
    {% comment %} Stripe script {% endcomment %}
    <script src="https://js.stripe.com/v3/"></script>
    <style type="text/css">
      html,
      body,
      header,
      .carousel {
        height: 60vh;
      }

      @media (max-width: 740px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }

      @media (min-width: 800px) and (max-width: 850px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }
    </style>
  </head>
<body>
  
  {% include 'includes/navbar.html' %}


    {% block content %} {% endblock %}
    {% block extra_body %}
    {% endblock %}
    
  
  {% include 'includes/footer.html' %}

  {% include 'includes/scripts.html' %}

  {% block extra_scripts %}
  {% endblock extra_scripts %}
  </body>
</html>

templates/home-page.html
{% extends 'base.html' %} 
{% block content%}

  <!--Main layout-->
  <main>
    <div class="container">
      <!--Navbar-->
      <nav
        class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5"
      >
        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#basicExampleNav"
          aria-controls="basicExampleNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">
          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#"
                >All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>
          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input
                class="form-control mr-sm-2"
                type="text"
                placeholder="Search"
                aria-label="Search"
              />
            </div>
          </form>
        </div>
        <!-- Collapsible content -->
      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row wow fadeIn">

        {% for item in items %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card">
              <!--Card image-->
              <div class="view overlay">
                <img
                  src="{{item.image.url}}"
                  class="card-img-top"
                  alt=""
                />
                <a href="{{item.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{item.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{item.get_absolute_url}}" class="dark-grey-text"
                      >{{item.title}}
                      <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                {% if item.discount_price %}
                  <strong>{{item.discount_price}}$</strong>
                {% else %}
                  <strong>{{item.price}}$</strong>
                {% endif %}
                </h4>
              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
          <!--Grid column-->
          {% endfor %}
          
        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row wow fadeIn">
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card">
              <!--Card image-->
              <div class="view overlay">
                <img
                  src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13.jpg"
                  class="card-img-top"
                  alt=""
                />
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>Shirt</h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text"
                      >Denim shirt
                      <span class="badge badge-pill danger-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>120$</strong>
                </h4>
              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card">
              <!--Card image-->
              <div class="view overlay">
                <img
                  src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/14.jpg"
                  class="card-img-top"
                  alt=""
                />
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>Sport wear</h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text">Sweatshirt</a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>139$</strong>
                </h4>
              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card">
              <!--Card image-->
              <div class="view overlay">
                <img
                  src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15.jpg"
                  class="card-img-top"
                  alt=""
                />
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>Sport wear</h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text"
                      >Grey blouse
                      <span class="badge badge-pill primary-color"
                        >bestseller</span
                      >
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>99$</strong>
                </h4>
              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
          <!--Grid column-->

          <!--Fourth column-->
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card">
              <!--Card image-->
              <div class="view overlay">
                <img
                  src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                  class="card-img-top"
                  alt=""
                />
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>Outwear</h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text">Black jacket</a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>219$</strong>
                </h4>
              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
          <!--Fourth column-->
        </div>
        <!--Grid row-->
      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

    {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          {% for n in page_obj.paginator.page_range %}
            {% if page_obj.number == n %}
              <li class="page-item active">
                <a class="page-link" href="?page={{n}}">
                  {{n}}
                  <span class="sr-only">(current)</span>
                </a>
              </li>
            {% elif n > page_obj.number|add:-3 and n < page_obj.number|add:3 %}
              <li class="page-item">
                <a class="page-link" href="?page={{n}}">{{n}}</a>
              </li>
            {% endif %}
          {% endfor %}
          
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->
    </div>
  </main>
  <!--Main layout-->
  {% endblock %}

templates/item_list.html
{% extends 'base.html' %} {% block content %}
<h1>List of Items:</h1>

{% for item in items %} {{item}} {% endfor %} {% endblock %}

templates/order-summary.html
{% extends 'base.html' %} 
{% block content%}

  <!--Main layout-->
  <main>
    <div class="container">
      <div class="table-responsive text-nowrap">
        <h2>Order Summary</h2>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Item title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total Item Price</th>
            </tr>
            </thead>
            <tbody>
            {% for order_item in object.items.all %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{order_item.item.title}}</td>
                <td>
                {% if order_item.item.discount_price %}
                    ${{order_item.item.discount_price}}
                {% else %}
                    ${{order_item.item.price}}
                {% endif %}
                </td>
                <td>
                    <a href={% url 'core:remove-single-product_url' slug=order_item.item.slug %}><i class="fas fa-minus-square mr-2"></i></a>
                        {{order_item.quantity}}
                    <a href={% url 'core:add-product_url' slug=order_item.item.slug %}><i class="fas fa-plus-square ml-2"></i></a>
                </td>
                <td>
                ${{order_item.get_total_price}}
                  <a style='color:red;' href={% url 'core:remove-product_url' slug=order_item.item.slug %}><i class="fas fa-trash float-right"></i></a>
                </td>

            </tr>
            {% empty %}
            <tr>
                <td colspan='5'><strong>Your cart is empty</strong></td>
            </tr>
            <tr>
                <td colspan='5'>
                <a class='btn btn-primary float-right' href={% url 'core:item-list_url' %}>Continue shopping</a>
                </td>
            </tr>
            {% endfor %}

            {% if object.coupon %}
            <tr>
                <td colspan='4'><strong>Coupon:</strong></td>
                <td><strong>-${{object.coupon.amount}}</strong></td>
            </tr>
            {% endif %}

            {% if object.get_total %}
            <tr>
                <td colspan='4'><strong>Order Total:</strong></td>
                <td><strong>${{object.get_total}}</strong></td>
            </tr>
            <tr>
                <td colspan='5'>
                <a class='btn btn-warning float-right ml-2' href={% url 'core:checkout_url' %}>Proceed to checkout</a>
                <a class='btn btn-primary float-right' href={% url 'core:item-list_url' %}>Continue shopping</a>
                </td>
            </tr>
            {% endif %}
            </tbody>
        </table>

        </div>
    </div>
  </main>
  <!--Main layout-->
  {% endblock %}

templates/product-page.html
{% extends 'base.html' %} {% block content%}
  
    <!--Main layout-->
    <main class="mt-5 pt-4">
      <div class="container dark-grey-text mt-5">
        <!--Grid row-->
        <div class="row wow fadeIn">
          <!--Grid column-->
          <div class="col-md-6 mb-4">
            <img
              src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg"
              class="img-fluid"
              alt=""
            />
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6 mb-4">
            <!--Content-->
            <div class="p-4">
              <div class="mb-3">
                <a href="">
                  <span class="badge purple mr-1">{{item.get_category_display}}</span>
                </a>
                <a href="">
                  <span class="badge blue mr-1">New</span>
                </a>
                <a href="">
                  <span class="badge red mr-1">Bestseller</span>
                </a>
              </div>

              <p class="lead">
              {% if item.discount_price %}
                <span class="mr-1">
                  <del>${{item.price}}</del>
                </span>
                <span>${{item.discount_price}}</span>
              {% else %}
                <span>${{item.price}}</span>
              {% endif%}
              </p>

              <p class="lead font-weight-bold">Description</p>

              <p>{{item.description}}</p>

              <form class="d-flex justify-content-left">
                <!-- Default input -->
                <input
                  type="number"
                  value="1"
                  aria-label="Search"
                  class="form-control"
                  style="width: 100px"
                />
                <button class="btn btn-primary btn-md my-0 p" type="submit">
                  Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>
              </form>

              <a href={{item.get_add_to_cart_url}} class="btn btn-primary btn-md my-0 p" type="submit">
                  Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
              </a>

              <a href={{item.get_remove_from_cart_url}} class="btn btn-danger btn-md my-0 p" type="submit">
                  Remove from cart
                  <i class="fas fa-shopping-cart ml-1"></i>
              </a>
            </div>
            <!--Content-->
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr />

        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">
          <!--Grid column-->
          <div class="col-md-6 text-center">
            <h4 class="my-4 h4">Additional information</h4>

            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus
              suscipit modi sapiente illo soluta odit voluptates, quibusdam
              officia. Neque quibusdam quas a quis porro? Molestias illo neque
              eum in laborum.
            </p>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row wow fadeIn">
          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4">
            <img
              src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
              class="img-fluid"
              alt=""
            />
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
            <img
              src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
              class="img-fluid"
              alt=""
            />
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
            <img
              src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
              class="img-fluid"
              alt=""
            />
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
    </main>
    <!--Main layout-->

    {% endblock %}

templates/request-refund.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block content%}

  <!--Main layout-->
  <main>
    <div class="container">
      <div class="table-responsive text-nowrap">
        <h2>Request Refund</h2>
        <form method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class='btn btn-primary'>Submit</button>
        </form>

        </div>
    </div>
  </main>
  <!--Main layout-->
  {% endblock %}